#!/usr/bin/env ruby

require 'securerandom'
require 'iora'

# ----- command line -----

CMD   = __FILE__.split("/").last
DIR   = File.expand_path(ARGV[0])
USAGE = "Usage: #{CMD} <trial_dir>"

abort USAGE if ARGV.length != 1
abort "#{USAGE}\nERROR: #{ARGV[0]} not a directory" unless File.directory?(DIR)

# ----- filepaths -----

TRIAL_DIR = DIR
DOC_DIR   = "Meditation"
TIMESTAMP = Time.now.strftime("%d%H%M%S")
TASK_FILE = "#{TRIAL_DIR}/.trial_data/meditation_tasks_#{TIMESTAMP}.yml"
TERM_FILE = "#{TRIAL_DIR}/.trial_data/meditation_terms_#{TIMESTAMP}.yml"
LCL_SETTINGS = File.expand_path(__dir__) + "/meditations_settings.yml"

puts "TRIAL DIR IS #{TRIAL_DIR}"
puts "DOC DIR IS #{DOC_DIR}"

# ----- settings and libraries -----

puts "ESTABLISH MEDITATIONS SETTINGS FOR #{TRIAL_DIR}"

Dir.chdir TRIAL_DIR
system "mkdir -p #{DOC_DIR}"
system "mkdir -p .trial_data/archive"
system "mv .trial_data/*meditation* .trial_data/archive 2> /dev/null"
system "cp #{LCL_SETTINGS} #{TRIAL_DIR}/.trial_data"

require_relative '../../exercise/Base/lib/trial_settings'
require_relative './meditations_text'

DOC_SRC  = MeditationsText.new

# ----- execution -----

Dir.chdir DOC_DIR

def fname(idx)
  maxpad = TS.num_exercise_docs.to_s.length
  zpad = idx.to_s.rjust(maxpad, "0")
  "file#{zpad}_#{TIMESTAMP}.html"
end

puts "GENERATE DOCS INTO DIRECTORY #{TS.trial_dir}/#{DOC_DIR}"
(1..TS.meditations_num_docs).to_a.each do |idx|
  File.open(fname(idx), "w") {|f| f.puts DOC_SRC.marked_para}
  print '.'
end
puts ''

puts "GENERATE TASKS INTO FILE #{TASK_FILE}"
Dir.chdir TS.trial_dir
File.open(TASK_FILE, 'w') do |f|
  f.puts "---"
  Dir.glob("#{DOC_DIR}/*#{TIMESTAMP}.html").each do |fn|
    title = fn.split('/').last.split('.').first
    url   = "http://#{TS.repo_url}/blob/master/#{fn}"
    line1 = %Q[Please remove html tags from file "#{fn}".<br/>]
    link1 = %Q[view file on <a href="#{url}">GitHub</a>]
    body =  "#{line1} ( #{link1} )<p><p/>/#{SecureRandom.hex(3)}"
    f.puts "- title:  Strip tags from #{title}"
    f.puts "  labels: EXERCISE,MEDITATIONS"
    f.puts "  body:   '#{body}'"
    print '.'
  end
end
puts ''

puts "GENERATE TERMS INTO FILE #{TERM_FILE}"
tasks = YAML.load_file(TASK_FILE)
File.open(TERM_FILE, 'w') do |f|
  f.puts "---"
  tasks.each do |task|
    f.puts "- price:  #{TS.meditations_price}"
    f.puts "  volume: #{TS.meditations_volume}"
    f.puts "  hexid:  #{Iora.hexid_for(task)}"
    print '.'
  end
end
puts ''

puts 'DONE'
