#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0

gemfile() {
  gem1=~/src/bugmark/exchange/Gemfile
  gem2=~/src/exchange/Gemfile
  [ -f $gem1 ] && echo "$gem1" || echo "$gem2"
}

echo "GEMFILE IS $(gemfile)"

export BUNDLE_GEMFILE=$(gemfile)

bundle exec rackup -p 4567 -o 0.0.0.0
