#!/usr/bin/env ruby

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
require 'awesome_print'

# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
puts 'EXERCISE SETTINGS'
ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails

puts 'LOADING IORA'
require 'iora'

# ----- expired offers -----
puts 'MARK ALL EXPIRED OFFERS'
Offer.open.expired_by_time.each do |offer|
  offer.update_attribute(:status, 'expired')
  print "."
end
puts ""

# ----- resolve -----

puts 'RESOLVE ALL EXPIRED/UNRESOLVED CONTRACTS'
Contract.expired.unresolved.each do |contract|
  result = ContractCmd::Resolve.new(contract).project
  if result.contract.awardee == 'fixed'
    funder = contract.positions.unfixed.first.user
    UserCmd::Deposit.new(uuid: funder.uuid, amount: 15.0).project
  end
  print "."
end
puts ""
