#!/usr/bin/env ruby

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
require 'awesome_print'
require 'securerandom'
require './user_gen_scr_setting'
include UserGenerationSettings

# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
#puts 'EXERCISE SETTINGS'
#ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails

# ----- accounts -----
puts 'CREATE A BUGMARK USER ACCOUNT'


(1..$numberofusers).each do |i|
  username= SecureRandom.hex(2)
  userpassword = SecureRandom.hex(2)
  opts = {
    balance: $userbalance,
    name: username,
    email: username+'@test.com',
    password: userpassword
  }
  userid = FB.create(:user, opts).user.id
  # update user jfields through sql
  sql = "UPDATE users SET jfields = '{\"skill\":#{$skills.sample($numberofskills)},
  \"password\":\"#{userpassword}\",\"type\":\"#{$usertype}\",
  \"treatment\":\"#{$usertreatment}\"}' WHERE id='#{userid}';"
  ActiveRecord::Base.connection.execute(sql).to_a
end
puts 'DONE'
