#!/usr/bin/env ruby

# SCRIPT NOT USED as of 2018-09-13 - table is generated within the exchange


# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
#puts 'EXERCISE SETTINGS'
#ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails


# ----- accounts -----
puts 'Create a Issue Comments Table in Database'

sql = "CREATE TABLE issue_comments
	(id SERIAL primary key not null,
		issue_uuid character varying not null,
		user_uuid character varying not null,
    user_name character varying not null,
    comment text not null,
    comment_date timestamp not null,
		comment_delete timestamp);"
ActiveRecord::Base.connection.execute(sql).to_a
puts 'DONE'
