#!/usr/bin/env ruby
# SPDX-License-Identifier: MPL-2.0

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
#puts 'EXERCISE SETTINGS'
#ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails


# ----- Reset Everything -----
puts 'Resetting Bugmark Exchange'

sql = "TRUNCATE TABLE
  amendments
, ar_internal_metadata
, bugmtimes
, contracts
, escrows
, events
, issue_comments
, issues
, log
, offers
, positions
, projections
, schema_migrations
, trackers
, user_groups
, user_memberships
, users
, work_queues
RESTART IDENTITY CASCADE;"
ActiveRecord::Base.connection.execute(sql)

BugmHost.reset

# ----- Delete graph images -----
Dir.glob("#{TS.graph_file_for_webapp_public}*.png").each { |file|
  File.delete(file)
}










puts 'DONE'
