#!/usr/bin/env ruby

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
require 'awesome_print'
require 'securerandom'

# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
puts 'EXERCISE SETTINGS'
ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails

# ----- accounts -----
def pwd_for(email)
  name = email.split("@").first
  "bugmark-#{name}"
end

puts 'CREATE A BUGMARK FUNDER ACCOUNT'
opts = {
  balance: 10000,
  email: TS.funder_email,
  password: pwd_for(TS.funder_email)
}
FB.create(:user, opts).user

puts 'CREATE BUGMARK WORKER ACCOUNTS'
TS.participants.each do |email|
  smail = email.chomp.strip
  FB.create(:user, email: smail, password: pwd_for(smail), name: SecureRandom.hex(2), balance: 50)
  print '.'
end
puts ''

puts 'DONE'
