#!/usr/bin/env ruby

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
#puts 'EXERCISE SETTINGS'
#ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails


# ----- accounts -----
puts 'Create a Work Queue Table in Database'

sql = "CREATE TABLE work_queue
	(id SERIAL primary key not null,
    user_uuid character varying not null,
    issue_uuid character varying not null,
    task character varying not null,
    added_queue timestamp not null,
    position int,
    canceled boolean default false,
    completed timestamp not null,
    startwork timestamp not null,
    updated_issue boolean default false);"
ActiveRecord::Base.connection.execute(sql).to_a
puts 'DONE'
