#!/usr/bin/env ruby

# ----- setup -----

Dir.chdir File.expand_path(__dir__)
require_relative '../../Base/lib/dotenv'
TRIAL_DIR = dotenv_trial_dir(__dir__)

# ----- libraries -----

require_relative '../../Base/lib/exchange'
require_relative '../../Base/lib/trial_settings'
# ----- info -----

puts "EXCHANGE_DIR=#{Exchange.src_dir}"
#puts 'EXERCISE SETTINGS'
#ap TrialSettings.settings

# ----- load -----

puts 'LOADING RAILS'
Exchange.load_rails


# ----- accounts -----
puts 'Update a Work Queue Table in Database'
loop do
	sql = "UPDATE work_queues
		SET updated_issue = true
		WHERE completed < now() and
		updated_issue = false;"
		ActiveRecord::Base.connection.execute(sql).to_a
		sleep 1
end
puts 'DONE'
