{
 "title": "Test environment",
 "time": { "from": "2019-03-05T17:53:56.000Z", "to": "2019-04-23T22:14:05.000Z" },
 "templating": {
  "list": [
   { "name": "project", "query": "select uuid from trackers;" },
   { "name": "project_name", "query": "select name from trackers;" }
  ]
 },
 "panels": [
  {
   "title": "Average Prices for Offers by Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Project: $tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "avgprice" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Price Ranges for Offers for \"$project_name\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "min price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "minprice" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "average price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "avgprice" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "max price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "maxprice" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Open Offers at End of Day by Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Project: $tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "offer_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Offers for \"$project_name\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of open offers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "offer_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks Available by Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Project: $tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "tasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Skills Demanded for \"$project_name\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_skill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "skill" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "tasks" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  },
  {
   "title": "New Messages by Project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Project: $tag_project_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "new_comments" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New Messages for \"$project_name\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of new messages",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "project_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "new_comments" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Payouts from Maturing Contracts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "tokens paid total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "potential_contract" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "tokens paid to workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "payout_contract" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Open Issues at End of Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of open issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "open_issues" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Volumes of Open Offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "minvol" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "avgvol" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "maxvol" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Percentage of Issues With no Activity in 14 days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "percentage of all open issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "abandoned_vs_open" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Contract Fix Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "percentage of contracts paid fixed side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "GraphData",
     "rawSql": "SELECT\n  $__time(maturation),\n  count(status)\nFROM\n  Contracts\nWHERE\n  status = 'resolved';",
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Days Until First Response to a New Issue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "average days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "first_response_days" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Maturation Days Offer Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "select age(CAST(co.maturation as date), CAST($__timeTo() as date)) as in_days,\r\n(select price from positions\r\njoin amendments\r\non positions.amendment_uuid = amendments.uuid\r\njoin contracts as ci\r\non amendments.contract_uuid = ci.uuid\r\njoin issues\r\non ci.stm_issue_uuid=issues.uuid\r\nwhere positions.side = 'unfixed'\r\nand issues.stm_tracker_uuid = '[[project]]'\r\nand ci.maturation = co.maturation\r\norder by positions.updated_at DESC limit 1) as LastPrice, max(positions.price) as HighPrice, min(positions.price) as LowPrice, sum(positions.volume) as Volume\r\nfrom positions\r\njoin amendments\r\non positions.amendment_uuid = amendments.uuid\r\njoin contracts as co\r\non amendments.contract_uuid = co.uuid\r\njoin issues\r\non co.stm_issue_uuid=issues.uuid\r\nwhere positions.side = 'unfixed'\r\nand issues.stm_tracker_uuid = '[[project]]'\r\nand co.status = 'open'\r\ngroup by co.maturation\r\norder by in_days DESC\r\n;\r\n"
    }
   ]
  },
  {
   "title": "Number of Closed Issues Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of closed issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Age of Open Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "average days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "open_issue_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Issues Closed After Days",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "average days",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GraphData",
     "select": [
      [
       { "params": [ "issue_resolution_days" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  }
 ]
}